Models/ErrorViewModel.cs
namespace ToDoList.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/ListContext.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;


namespace ToDoList.Models
{
    public class ListContext:DbContext
    {
        public ListContext(DbContextOptions<ListContext> options)
            : base(options)
        { }
        public DbSet<TheList> GetItDone { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<TheList>().HasData(
                new TheList
                {
                    ID = 1,
                    Description = "Do CIT218 Homework",
                    CreatedDate = DateTime.Today
                },
                new TheList {
                    ID = 2,
                    Description="Take a nap",
                    CreatedDate = DateTime.Today
                },
               new TheList {
                    ID = 3,
                    Description = "Work Out",
                    CreatedDate = DateTime.Today
                }
                ); 
        }
     }
}

Models/TheList.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace ToDoList.Models
{
    public class TheList
    {
        [Required]
        public int ID { get; set; }

        [Required(ErrorMessage = "Please enter a description.")]
        public string? Description { get; set; }

        [Display(Name = "Created Date")]
        [DataType(DataType.Date)]
        public DateTime? CreatedDate { get; set; }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ToDoList.Models;

namespace ToDoList.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/TheListController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ToDoList.Models;

namespace ToDoList.Controllers
{
    public class TheListController : Controller
    {
        private readonly ListContext _context;

        public TheListController(ListContext context)
        {
            _context = context;
        }

        // GET: TheList
        public async Task<IActionResult> Index()
        {
            return View(await _context.GetItDone.ToListAsync());
        }

        // GET: TheList/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var theList = await _context.GetItDone
                .FirstOrDefaultAsync(m => m.ID == id);
            if (theList == null)
            {
                return NotFound();
            }

            return View(theList);
        }

        // GET: TheList/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: TheList/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Description,CreatedDate")] TheList theList)
        {
            if (ModelState.IsValid)
            {
                _context.Add(theList);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(theList);
        }

        // GET: TheList/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var theList = await _context.GetItDone.FindAsync(id);
            if (theList == null)
            {
                return NotFound();
            }
            return View(theList);
        }

        // POST: TheList/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Description,CreatedDate")] TheList theList)
        {
            if (id != theList.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(theList);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TheListExists(theList.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(theList);
        }

        // GET: TheList/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var theList = await _context.GetItDone
                .FirstOrDefaultAsync(m => m.ID == id);
            if (theList == null)
            {
                return NotFound();
            }

            return View(theList);
        }

        // POST: TheList/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var theList = await _context.GetItDone.FindAsync(id);
            _context.GetItDone.Remove(theList);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TheListExists(int id)
        {
            return _context.GetItDone.Any(e => e.ID == id);
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="p-3 m-0 bg-light bg-opacity-75 rounded-3 text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - To Do List</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/custom.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
    <header>
        <img src="~/Images/abstract.png" style="position:absolute;left:0px;top:0px;height:100%;width:100%;z-index:-1;" />
        <nav class="navbar navbar-dark navbar-expand-sm navbar-toggleable-sm text-light border-bottom box-shadow mb-3" >
            <div class="container">
                <a class="navbar-brand text-light" asp-area="" asp-controller="TheList" asp-action="Index"><i class="fa fa-edit" style="font-size:36px"></i></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="TheList" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3 text-dark">
                @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - ToDoList - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Views/TheList/Create.cshtml
@model ToDoList.Models.TheList

@{
    ViewData["Title"] = "Create";
}

<div class="p-3 m-0 bg-light bg-opacity-50">
    <h1 class="p-3">Add to the List</h1>
</div>
<div class="p-3 m-0 bg-light bg-opacity-75 rounded-3">
    <h4>Add another task...</h4>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Description" class="control-label"></label>
                    <input asp-for="Description" class="form-control" />
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="CreatedDate" class="control-label"></label>
                    <input asp-for="CreatedDate" class="form-control" />
                    <span asp-validation-for="CreatedDate" class="text-danger"></span>
                </div>
                <div class="form-group mt-2">
                    <input type="submit" value="Create" class="btn btn-primary" />
                    <a asp-action="Index">Back to List</a>
                </div>
            </form>
        </div>
    </div>

</div>
    @section Scripts {
        @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    }

Views/TheList/Delete.cshtml
@model ToDoList.Models.TheList

@{
    ViewData["Title"] = "Delete";
}

<div class="p-3 m-0 bg-light bg-opacity-50">
    <h1>Delete Item</h1>
</div>
<div class="p-3 m-0 bg-light bg-opacity-75 rounded-3">
    <h3>Are you sure you want to delete this?</h3>
    <div>
        <hr />
        <dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Description)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Description)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.CreatedDate)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.CreatedDate)
            </dd>
        </dl>

        <form asp-action="Delete">
            <input type="hidden" asp-for="ID" />
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            <a asp-action="Index">Back to List</a>
        </form>
    </div>
</div>

Views/TheList/Details.cshtml
@model ToDoList.Models.TheList

@{
    ViewData["Title"] = "Details";
}

<div class="p-3 m-0 bg-light bg-opacity-50">
    <h1>Item Details</h1>
</div>
<div class="p-3 m-0 bg-light bg-opacity-75 rounded-3">
    <div>
        <h4>To Do List</h4>
        <hr />
        <dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Description)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Description)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.CreatedDate)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.CreatedDate)
            </dd>
        </dl>
    </div>
    <div>
        <a asp-action="Edit" asp-route-id="@Model.ID">Edit</a> |
        <a asp-action="Index">Back to List</a>
    </div>
</div>

Views/TheList/Edit.cshtml
@model ToDoList.Models.TheList

@{
    ViewData["Title"] = "Edit";
}

<div class="p-3 m-0 bg-light bg-opacity-50">
    <h1>Edit item</h1>
</div>
<div class="p-3 m-0 bg-light bg-opacity-75 rounded-3">
    <h4>To Do List</h4>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Edit">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="ID" />
                <div class="form-group">
                    <label asp-for="Description" class="control-label"></label>
                    <input asp-for="Description" class="form-control" />
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="CreatedDate" class="control-label"></label>
                    <input asp-for="CreatedDate" class="form-control" />
                    <span asp-validation-for="CreatedDate" class="text-danger"></span>
                </div>
                <div class="form-group mt-2">
                    <input type="submit" value="Save" class="btn btn-primary" />
                    <a asp-action="Index">Back to List</a>
                </div>
            </form>
        </div>
    </div>

</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/TheList/Index.cshtml
@model IEnumerable<ToDoList.Models.TheList>

@{
    ViewData["Title"] = "Index";
}
<div class="p-3 m-0 bg-light bg-opacity-50">
    <h1>To Do List</h1>
</div>
<div class="p-3 m-0 bg-light bg-opacity-50 rounded-3">
    <p>
        <a  asp-action="Create">Create New Item</a>
    </p>

    <table class="table">

        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Description)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CreatedDate)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Description)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CreatedDate)
                    </td>
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                        <a asp-action="Details" asp-route-id="@item.ID">Details</a> |
                        <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>